# Generated by Django 5.2.5 on 2025-08-21 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Manzil"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Ro'yxatdan o‘tgan vaqt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="father_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Otasining ism-familiyasi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="father_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Otasining telefon raqami",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "O'g'il bola"), ("female", "Qiz bola")],
                default=1,
                max_length=6,
                verbose_name="Jinsi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="mother_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Onasining ism-familiyasi",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mother_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Onasining telefon raqami",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default=1, max_length=20, verbose_name="Telefon"),
            preserve_default=False,
        ),
    ]
